version: '3.9'
services:
  db:
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sabaoempoWaschpulver
      MYSQL_DATABASE: demoProjectDB
      MYSQL_USER: braga
      MYSQL_PASSWORD: sabaoempoWaschpulver
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: